language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env: MINIMUM_VERSIONS=false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3


install:
  - composer install --no-interaction

script:
  - composer run test
